# Basic, no-op receiver. Edit to add your notification channels (email, Slack, Telegram, webhooks).
route:
  receiver: "null"
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: "null"
    # Example:
    # email_configs:
    #   - to: "ops@example.com"
