global:
  scrape_interval: 15s
  evaluation_interval: 30s
  external_labels:
    cluster: "default"

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Scrape the snmp-exporter (you will pass SNMP target via query params)
  - job_name: "snmp-exporter"
    static_configs:
      - targets: ["snmp-exporter:9116"]
