apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: InfluxDB (Telegraf)
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: ${INFLUXDB_DB}
    user: ${INFLUXDB_USER}
    secureJsonData:
      password: ${INFLUXDB_PASSWORD}
    jsonData:
      httpMode: POST
      timeInterval: 10s
    editable: true
  - name: InfluxDB (Proxmox)
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: ${INFLUXDB_PROXMOX_DB}
    user: ${INFLUXDB_PROXMOX_USER}
    secureJsonData:
      password: ${INFLUXDB_PROXMOX_PASSWORD}
    jsonData:
      httpMode: POST
      timeInterval: 10s
    editable: true